// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mock_service is a generated GoMock package.
package mock_service

import (
	reflect "reflect"

	models "github.com/deuuus/bmsru-rsoi-lab2/src/loyalty/internal/models"
	gomock "github.com/golang/mock/gomock"
)

// MockLoyalty is a mock of Loyalty interface.
type MockLoyalty struct {
	ctrl     *gomock.Controller
	recorder *MockLoyaltyMockRecorder
}

// MockLoyaltyMockRecorder is the mock recorder for MockLoyalty.
type MockLoyaltyMockRecorder struct {
	mock *MockLoyalty
}

// NewMockLoyalty creates a new mock instance.
func NewMockLoyalty(ctrl *gomock.Controller) *MockLoyalty {
	mock := &MockLoyalty{ctrl: ctrl}
	mock.recorder = &MockLoyaltyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLoyalty) EXPECT() *MockLoyaltyMockRecorder {
	return m.recorder
}

// GetLoyaltyStatus mocks base method.
func (m *MockLoyalty) GetLoyaltyStatus(username string) (*models.LoyaltyStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoyaltyStatus", username)
	ret0, _ := ret[0].(*models.LoyaltyStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoyaltyStatus indicates an expected call of GetLoyaltyStatus.
func (mr *MockLoyaltyMockRecorder) GetLoyaltyStatus(username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoyaltyStatus", reflect.TypeOf((*MockLoyalty)(nil).GetLoyaltyStatus), username)
}

// UpdateReservationCount mocks base method.
func (m *MockLoyalty) UpdateReservationCount(username string, acc int) (*models.LoyaltyStatusShort, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReservationCount", username, acc)
	ret0, _ := ret[0].(*models.LoyaltyStatusShort)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateReservationCount indicates an expected call of UpdateReservationCount.
func (mr *MockLoyaltyMockRecorder) UpdateReservationCount(username, acc interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReservationCount", reflect.TypeOf((*MockLoyalty)(nil).UpdateReservationCount), username, acc)
}
